from typing import Protocol

from app.domain import DocStructure


class IDocStorage(Protocol):
    async def load_structure(self) -> list[DocStructure]: ...
    async def load_file(self, root_relative_path: str) -> str: ...
    async def save_file(self, root_relative_path: str, data: str) -> None: ...
    async def delete_file(self, root_relative_path: str) -> None: ...
