version: '3.8'

services:
  aidoc-api:
    image: ghcr.io/sergeikrivko/aidoc-api:main
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80;https://+:443
